# Generated by Django 4.2.4 on 2023-08-16 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_card_set_remove_usercollection_card_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card',
        ),
    ]
