# Generated by Django 4.2.4 on 2023-08-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_card_set'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='images',
            new_name='image',
        ),
        migrations.AddField(
            model_name='card',
            name='card_id',
            field=models.CharField(default='default_card_id', max_length=100),
        ),
    ]
