# Generated by Django 4.2.4 on 2023-08-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0009_set_releasedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='set_logos/'),
        ),
    ]
