# Generated by Django 4.2.4 on 2023-08-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0010_set_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='logo',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
